release:

before:
  hooks:
    - go mod tidy

builds:
- id: kubecolor
  main: ./cmd/kubecolor/main.go
  binary: kubecolor
  ldflags:
    - -s -w
    - -X main.Version={{.Version}}
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - arm64
    - amd64
    - ppc64le

archives:
- builds:
  - kubecolor
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip

brews:
- name: kubecolor
  tap:
    owner: kubecolor
    name: homebrew-tap
    token: "{{ .Env.GLOBAL_GITHUB_TOKEN }}"
  homepage: "https://github.com/golonzovsky/kubecolor"
  description: "Colorize your kubectl output"
  license: "MIT"
  folder: Formula
  install: |
    bin.install "kubecolor"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
