release:
  prerelease: auto

before:
  hooks:
    - go mod tidy

builds:
- id: kubecolor
  main: ./cmd/kubecolor/kubecolor.go
  binary: kubecolor
  ldflags:
    - -s -w
    - -X main.Version={{.Version}}
  env:
    - CGO_ENABLED=0
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - arm64
    - amd64
    - ppc64le

archives:
- builds:
  - kubecolor
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
